CREATE TABLE `orders` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`order_number` text NOT NULL,
	`requester_name` text NOT NULL,
	`requester_phone` text NOT NULL,
	`requester_email` text NOT NULL,
	`payer_name` text NOT NULL,
	`payer_nip` text NOT NULL,
	`payer_contractor_id` integer,
	`object_name` text NOT NULL,
	`object_address` text,
	`object_city` text,
	`object_location_url` text,
	`object_id` integer,
	`contact_person` text NOT NULL,
	`contact_phone` text NOT NULL,
	`contact_email` text,
	`is_camera_installation` integer DEFAULT false,
	`camera_count` integer,
	`megaphone_count` integer,
	`vtools_offer_number` text,
	`monthly_amount` real,
	`rental_amount` real,
	`invoice_issuer` text,
	`status` text DEFAULT 'new' NOT NULL,
	`service_start_date` text,
	`notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`payer_contractor_id`) REFERENCES `contractors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`object_id`) REFERENCES `objects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `orders_order_number_unique` ON `orders` (`order_number`);